### ISSUE TITLE
Exception in ds play command (2)

### ISSUE THREAD

**Issue by HuyaneMatsu** [HuyaneMatsu/Koishi#29]
`ds play` command might raise the following exception:

```py3
Koishi#8708 ignores occurred exception at `Slasher` while calling `<SlashCommandFunction name='play', description='Starts the game', is_default=True>`
Traceback (most recent call last):
  File ".../hata/ext/slash/command/slash_command/slash_command_function.py", line 161, in invoke
    await process_command_coroutine(
        client,
        interaction_event,
        self.response_modifier,
        command_coroutine,
    )
  File ".../hata/ext/slash/responding.py", line 369, in process_command_coroutine
    response = await coroutine
  File ".../bots/modules/dungeon_sweeper_v2.py", line 4124, in play
    await game.renew(event)
  File ".../bots/modules/dungeon_sweeper_v2.py", line 3780, in renew
    embed, components = user_state.game_state.render_playing()
  File ".../bots/modules/dungeon_sweeper_v2.py", line 2612, in render_playing
    button_skill = self.button_skill_get()
  File ".../bots/modules/dungeon_sweeper_v2.py", line 2524, in button_skill_get
    elif chapter.skill_can_activate(self):
  File ".../bots/modules/dungeon_sweeper_v2.py", line 901, in FLAN_SKILL_CAN_ACTIVATE
    target_tile = map_[position + step]
IndexError('list index out of range')
```

**Comment by HuyaneMatsu** [comment]
Same issue as #28.
