### ISSUE TITLE
unhandled exception at clear command

### ISSUE THREAD

**Issue by HuyaneMatsu** [HuyaneMatsu/Koishi#31]
```py3
Koishi#8708 ignores occurred exception at `Slasher` while calling `<SlashCommandFunction name='clear', description='Yeets messages.', response_modifier=<ResponseModifier allowed_mentions=None show_for_invoking_user_only=True>>`
Traceback (most recent call last):
  File ".../hata/ext/slash/command/slash_command/slash_command_function.py", line 161, in invoke
    await process_command_coroutine(
        client,
        interaction_event,
        self.response_modifier,
        command_coroutine,
    )
  File ".../hata/ext/slash/responding.py", line 361, in process_command_coroutine
    response = await process_command_coroutine_generator(
        client,
        interaction_event,
        response_modifier,
        coroutine,
    )
  File ".../hata/ext/slash/responding.py", line 286, in process_command_coroutine_generator
    response = await step
  File ".../bots/modules/administration.py", line 88, in clear
    await client.multi_client_message_delete_sequence(channel, after=after, before=before, limit=limit, filter=filter,
        reason=reason)
  File ".../hata/discord/client/compounds/message.py", line 1472, in multi_client_message_delete_sequence
    result = task.result()
  File ".../hata/discord/http/http_client.py", line 623, in message_delete_b2wo
    return await self.discord_request(
        StackedStaticRateLimitHandler(RATE_LIMIT_GROUPS.static_message_delete_b2wo, channel_id),
        METHOD_DELETE,
        f'{API_ENDPOINT}/channels/{channel_id}/messages/{message_id}',
        reason = reason,
    )
  File ".../hata/discord/http/http_client.py", line 313, in discord_request
    raise DiscordException(response, response_data, data, self._debug_options)
DiscordException Not Found (404), code=10003: Unknown Channel
2022-08-23 01:16:23; DELETE https://discord.com/api/v10/channels/999568878596276247/messages/1006228577735417998
```

**Comment by HuyaneMatsu** [comment]
Fixed 👌🏻
